# Project: BinaryTree
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = BinaryTree.o Reality.o
LINKOBJ  = BinaryTree.o Reality.o
LIBS     = -L"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib" -L"E:/MyDownloads/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/MyDownloads/Download/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = BinaryTree.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

BinaryTree.o: BinaryTree.cpp
	$(CPP) -c BinaryTree.cpp -o BinaryTree.o $(CXXFLAGS)

Reality.o: Reality.cpp
	$(CPP) -c Reality.cpp -o Reality.o $(CXXFLAGS)
